Documentation
ut-robotics/picr22-team-saga pull request #61
Opened 2023-01-15 12:25 UTC by AnishShr

2023-01-15 12:56 UTC, ReikoR requested changes

2023-01-15 12:56 UTC, ReikoR commented on README.asciidoc
> +`OpenCV` to interfce the in-built libraries for computer vision     +
interfce -> interface

2023-01-15 12:56 UTC, ReikoR commented on README.asciidoc
> +`Pyrealsense2` to interfc the Realsense Camera and its configurations   +
interfc -> interface

2023-01-15 12:56 UTC, ReikoR commented on README.asciidoc
> +`Pyserial` for serial communication with the STM32 microcontoller over USB      +
microcontoller -> microcontroller

2023-01-15 12:56 UTC, ReikoR commented on README.asciidoc
> +This is the module responsible for the image processing operations and detecting colors for image segmentation. This module produces the processed iamge frame and all of its objects necessary for fur
iamge -> image

2023-01-15 12:56 UTC, ReikoR commented on README.asciidoc
> +An enum class defined to set the state at which the robot may be at an isntant.
isntant -> instant

2023-01-15 12:56 UTC, ReikoR commented on README.asciidoc
> +Initially, the robot is in the state: `FIND_A_BALL`. In this state, the robot searches the ball. If there is no ball to be seen in the processed camera frame, the it keeps rotating at the same place
the it -> then it

2023-01-15 13:14 UTC, AnishShr commented on README.asciidoc
> +`OpenCV` to interfce the in-built libraries for computer vision     +
corrected

2023-01-15 13:14 UTC, AnishShr commented on README.asciidoc
> +`Pyrealsense2` to interfc the Realsense Camera and its configurations   +
corrected

2023-01-15 13:14 UTC, AnishShr commented on README.asciidoc
> +`Pyserial` for serial communication with the STM32 microcontoller over USB      +
corrected

2023-01-15 13:14 UTC, AnishShr commented on README.asciidoc
> +This is the module responsible for the image processing operations and detecting colors for image segmentation. This module produces the processed iamge frame and all of its objects necessary for fur
corrected

2023-01-15 13:14 UTC, AnishShr commented on README.asciidoc
> +An enum class defined to set the state at which the robot may be at an isntant.
corrected

2023-01-15 13:14 UTC, AnishShr commented on README.asciidoc
> +The module which detects the state of teh robot at any current instant, taking the processed frame inputs from the `main.py` module, and acting accordingly waht to do when a robot is in a particular
corrected

2023-01-15 13:14 UTC, AnishShr commented on README.asciidoc
> +Initially, the robot is in the state: `FIND_A_BALL`. In this state, the robot searches the ball. If there is no ball to be seen in the processed camera frame, the it keeps rotating at the same place
corrected

2023-01-15 13:14 UTC, AnishShr commented on README.asciidoc
> +- Detection of farther basket and driving towards the oppsoite half when the ball is far could be better optimized
corrected

2023-01-15 13:14 UTC, AnishShr commented on README.asciidoc
> +However, the board had some problems. Firstly, the pads where the battery's positive terminal needed to be connected were left unconnected. Thus, this conenction needed to be provide by some other me
corrected

2023-01-15 13:14 UTC, AnishShr commented on README.asciidoc
> +The Electronics part comprises of two sub tasks:
corrected

2023-01-15 13:14 UTC, AnishShr commented on README.asciidoc
> +The test robot we received was in quite a bad codition. A lot of critical components and holes were either cut out or modified by mechanical means, so at first, taking the measurements for a test thr
corrected

2023-01-15 13:14 UTC, AnishShr commented on README.asciidoc
> +- The omniwheels were 3D printed, the rollers were pressure fitted which greatly decreases the parts complexity and increases the ease of servicability. The connecor which fastens the wheel to the mo
corrected

2023-01-15 13:15 UTC, AnishShr commented on README.asciidoc
> +<<<<<<< HEAD
cleaned

2023-01-15 13:15 UTC, AnishShr commented on README.asciidoc
> +<<<<<<< HEAD
cleaned

2023-01-15 13:16 UTC, AnishShr commented on README.asciidoc
> +>>>>>>> 73095bfb929ac4462d035fdb161416a2abb43a7f
Merge conflicts cleaned and blogs ordered in the correct chronological order.

2023-01-15 13:35 UTC, AnishShr commented on README.asciidoc
> +=== Personal comments
Personal comments added from my side.

2023-01-15 16:31 UTC, AnishShr commented on README.asciidoc
> +== Mechanics
Robot photo added

2023-01-15 17:20 UTC, ReikoR requested changes

2023-01-15 17:20 UTC, ReikoR commented on README.asciidoc
> +I mainly worked on the electronics design and software programming tasks, along with assembly of the test robot. This was my first time experience with the multi-layer PCB design, and especially the
* expereince -> experience
* dsigning - > designing

2023-01-15 17:20 UTC, ReikoR commented on README.asciidoc
> +Moreover, in the software programming task, it was a new experience for me as I have very little expereince in programming before. Even though I was familiar with ROS programming, here most of the th
expereince -> experience

2023-01-15 17:20 UTC, ReikoR commented on README.asciidoc
> +Personally, I feel prioritizing the tasks is an undermined skill which should be acknowledge by all. This makes the flow of the work more practical, as different category of tasks have distinct deadl
be acknowledge -> be acknowledged

2023-01-15 17:20 UTC, ReikoR commented on README.asciidoc
> +Also, revised cross-checking the electronics design is an important task that should be carried out. We missed out a connectionn in one of the power pads, which created a mess actually. So for next t
connectionn -> connection

2023-01-15 17:20 UTC, ReikoR commented on README.asciidoc
> +- Skim through the taks at the start so you would know what things you need to cover until the end of the project. If you need to acquire new skills, its better to start early.
taks -> tasks
its -> it's

2023-01-15 18:21 UTC, ReikoR commented on README.asciidoc
> +I mainly worked on the electronics design and software programming tasks, along with assembly of the test robot. This was my first time experience with the multi-layer PCB design, and especially the
expereience -> experience

2023-01-15 18:57 UTC, AnishShr commented on README.asciidoc
> +I mainly worked on the electronics design and software programming tasks, along with assembly of the test robot. This was my first time experience with the multi-layer PCB design, and especially the
corrected

2023-01-16 10:13 UTC, AnishShr commented on README.asciidoc
> +I mainly worked on the electronics design and software programming tasks, along with assembly of the test robot. This was my first time experience with the multi-layer PCB design, and especially the
All changes addressed and pushed.

2023-01-18 08:22 UTC, AnishShr commented on README.asciidoc
> +=== Personal comments
Probably no comments coming from Artem's side.

2023-01-18 09:01 UTC, ReikoR approved these changes

2023-01-18 09:16 UTC, merged